---
title: "LiteratureReview"
author: "Meaghan Burke, Justin Herman, Vikas Sinha, Joseph Garcia"
date: "October 19, 2019"
output:
  html_document: default
  pdf_document: default
---

## Research Question: 

Do publications negatively portray certain candidates more than other candidates?

## Literature Review

Our capstone project aims to measure bias in news media coverage for the candidates in the United
States 2020 Democratic Presidential Primary. The Literature Review section focuses on a selection
of published literature and analyses that define political bias and identify ways of measuring
and quantifying these biases. 

Many researchers have grappled with the difficulty of precisely measuring or documenting bias,
including Sutter [1]. Sutter compares bias in universities versus for-profit organizations.
He concludes that incentives for bias in academic
settings are of quite different than those in commercial settings. He advocates a number of
suggestions to mitigate this bias, taking into account the stakeholders in academia and 
their own incentives in mitigating or promoting bias.

### Causes of Bias

A number of papers, e.g. Sutter [1] and Baron [2], focus on the factors that cause
and sustain political bias. 
Sutter [1] compares the incentives for bias in universities versus those in for-profit
organizations, and concludes that the forces that sustain bias in academic work
are of a different nature than those that result in bias in commercial organizations. Since
the stakeholders and accountability structures are vastly different between these categories, this
is to be expected.

For Bernhardt [3], media bias is quite simply a result of partisan preference for biased news.
Baron [2] concludes that journalistic bias tends to lower subscription
prices, and therefore is sustainable only if it allows hiring of journalists at a lower wage.
Gentzkow et al [5] divide the causes of bias into supply-side and demand-side categories. 
Supply-side causes are related to the production of news media, such as practices of 
management or labor in news media organizations. Demand-side causes are those originating from
consumers' perceptions and preferences.

For bias to persist, there must be factors that sustain, or even strengthen it.
The task of identifying factors that sustain bias across the adaptive and dynamic
environment of news media organizations is the focus of papers such as Sutter [1], Baron [2],
Bernhardt [3], Baum and Groeling [4].

Sutter [1] suggests that journalism, the main transmission engine for ideas and information in
society, is inherently subjective and often reflects the opinions of the journalist and/or news
outlet. However, the evidence to prove the existence of bias is circumstantial, making the
measurement and quantification of these biases very difficult. Sutter notes that revenue is
a controlling force for limiting or reducing bias in privately-owned news media organizations.
He argues that the inclusion of too much bias in reporting can adversely affect the readership
and advertising revenue for the news organizations.

Like Sutter, Baron [2] submits that profit-maximizing, competitive pressures, consumer
preferences, and the general economic and financial landscapes impact the role of bias
in news media. Unlike Sutter, Baron theorizes that there are strong correlations between
political biases and consumer expectations, operational costs, and the ideological alignments
of the employed journalists. Baron's findings show that several forces combine to ensure
the presence and prevalence of unbalanced reporting.

Bernhardt [3] also suggests that profit-maximization may influence a news media outlet to
cater to a more partisan audience by suppressing or doctoring some pertinent information in
its news reporting. 

Baum and Groeling [4] submits that the advent of internet media removed the professional editorial
process from news content. The new "partisan" styled editorial system of internet news, paired
with the public's adoption of the internet, produced a more fragmented audience.


### Consequences of Bias

Several authors explain the different ways that political bias causes harm.
Bernhardt [3] cautions that the impact of media bias is more powerful and
determinative than commonly presumed, since its effect cannot be nullified, even to a rational
consumer.
Baum and Groeling's [4] study found that left-skewed and right-skewed political biases exist in
internet news media. This shift from bipartisan to partisan coverage has important implications
for political discourse in America and may impact the decision making for many Americans.

Like Baum and Groeling, Gentzkow and Shapiro [5] believe that media bias can have large effects on
voter behavior, public perception and political outcomes. However, it is very difficult to
determine the actual impact of these biases.

Stone [6] presents the counterintuitive thesis that bias can be more prevalent in certain
competitive media markets than in some less competitive ones. Stone presents formal proof
that consumers can, for example, be less informed in some media duopolies than in some
monopolies. Thus, one must guard against simplistic prescriptions on how to counter bias,
since its correlations with market conditions can be contrary to intuition.

Sheth's [7] initial findings are that media coverage is broadly anti-conservative. His model
also concludes that the news outlets, regardless of political affiliations, are resoundingly
negative and critical of the opposition instead of championing its respective candidates.
The Sheth model findings align with the general public's perception of media bias.

Lin, Bagrow and Lazer [8] prove that internet blogs are, more "social" as they are more connected
and consequently more influenced by site connections. Being more connected makes the internet
blogs more "exogenous", or more influenced by external factors, such as election cycles.


### Measuring Bias

Many researchers have grappled with the difficulty of precisely measuring or documenting bias.
A number of papers, such as Sheth[7], Lin [8], and O'Connor [9], focus on the problem of quantifying
media bias in networks, and present models that can be used to quantify political bias.

Sheth [7] proposes a model for measuring ideological bias in news coverage by mainstream media
outlets. Terms in the news articles are classified based on detected political affiliations:
pro-conservative, anti-conservative, pro-liberal and anti-liberal. Once classified, the model
detects the overall measurement of political bias in each article.

Lin, Bagrow and Lazer [8] propose a method of quantifying bias in both traditional news media and
internet blogs. The method primarily compares the number of media references to members of the
United States congress. This method helps reduce errors due to subjective criteria, such as
sentiment or degrees of bias. The presented method can also account for the variance in bias
over time. 

O'Connor, Balasubramanyan, Routledge and Smith [9] test how well Twitter sentiment correlates
with consumer confidence, presidential and election polling data. The highlighted sentiment
analysis model uses a lexicon from OpinionFinder on a tailored subset of Twitter data relating
to several political topics between the years 2008 and 2009. The topics include key words such
as "jobs", "Obama", "McCain", etc. The model calculates a sentiment score based on the ratio of
positive to negative words. Smoothing averages techniques remove sentiment score noise and can
help to determine correlation.  O'Connor, Balasubramanyan, Routledge and Smith note that
techniques like stemming caused dangerous misclassification over the model's lexicon, but
did not substantially affect the aggregated scoring composites.  The model proved effective
with predicting economic indicators, but exhibited difficulty predicting the presidential
approval polls.          

The model described by Groseclose and Milyo [10] calculates an ADA (Americans for Democratic Action)
score for various news outlets across the political spectrum.
In Groceclose and Milyo's research, ADA is coterminous with political slant or
liberal affiliation. The ADA score is calculated from the number of times the news media
outlet cites various think-tanks in articles, compared against the number of times Congress
cites the same think-tanks in Congressional speeches.  The citation patterns frequency
determines the news media outlet's political slant. In the study, editorials or traditional
opinionated pieces are omitted as these pieces intend to exhibit biased reporting. 


### References

1.	Sutter, D. (2012).Mechanisms of Liberal Bias in the News Media versus the Academy.http://www.independent.org/pdf/tir/tir_16_03_4_sutter.pdf
2.	Baron, D. P. (2004). Persistent media bias. Journal of Public Economics, 90 (2006), 1 - 36.  https://pdfs.semanticscholar.org/2abb/9660637a260e5342c3e2c00abb07ab903978.pdf
3.	Bernhardt, D., Krasa, S., Polborn, M. (2008). Political polarization and the electoral effects of media bias. Journal of Public Economics, 92 (2008), 1092 - 1104. http://www.econ.uiuc.edu/~skrasa/media_bias_december_2007.pdf
4.	Baum and Groeling (2008). New Media and the Polarization of American Political Discourse. https://journalistsresource.org/wp-content/uploads/2012/03/News-Media-and-Polarization-Matt-Baum_Political-Communication-LK.pdf
5.	Gentzkow and Shapiro. Media Bias in the Marketplace: Theory. https://web.stanford.edu/~gentzkow/research/handbook.pdf   
6.	Stone, D. (2011). Ideological media bias. Journal of Economic Behavior & Organization, 78 (2011), 256-271.
7.	Sheth, Dev. "Measuring Ideological Bias in News Coverage of Political Events by Print Media Using Data Analytics." Rochester Institute of Technology , 2016, pp. 1-21.
8.	Lin, Bagrow and Lazer (2011). More Voices Than Ever? Quantifying Media Bias in Networks. https://arxiv.org/pdf/1111.1227.pdf
9.	B. O'Connor, R. Balasubramanyan, B.R. Routledge, and N.A. Smith. From Tweets to Polls: Linking Text Sentiment to Public Opinion Time Series. https://homes.cs.washington.edu/~nasmith/papers/oconnor+balasubramanyan+routledge+smith.icwsm10.pdf
10.	Groseclose, T., Milyo, J. (2005). A measure of media bias. The Quarterly Journal of Economics, CXX (4), 1191-1237. http://itre.cis.upenn.edu/~myl/GrosecloseMilyo.pdf
